### ISSUE TITLE
Wrong commit author with utf8 characters

### ISSUE THREAD

**Issue by kesselb** [nextcloud/backportbot#159] opened 2020-03-08 17:36 UTC
![Screenshot from 2020-03-08 18-35-27](https://user-images.githubusercontent.com/3902676/76168021-a7a19180-616b-11ea-850b-ea73d3dd7974.png)

Example: https://github.com/nextcloud/documentation/pull/1871

**Comment by imba-tjd** [comment] 2020-03-09 01:45
Maybe it's my issue. The original commit I made was done on GitHub, which uses my "Name" setting on GitHub. But when rebase --signoff, it uses my PC's git config user.name which is my id. They are both set by myself.

**Comment by nickvergessen** [comment] 2020-03-31 09:27
Yeah, that sounds like it

**Comment by skjnldsv** [comment] 2024-01-23 14:59
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2024-01-23 14:59 UTC
